# Generated by Django 5.1.1 on 2024-09-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
